# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_conf_setting.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_serial_window(object):
    def setupUi(self, serial_window):
        serial_window.setObjectName("serial_window")
        serial_window.setWindowModality(QtCore.Qt.ApplicationModal)
        serial_window.resize(259, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(serial_window.sizePolicy().hasHeightForWidth())
        serial_window.setSizePolicy(sizePolicy)
        serial_window.setMaximumSize(QtCore.QSize(300, 250))
        serial_window.setBaseSize(QtCore.QSize(410, 410))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/logi_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        serial_window.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(serial_window)
        self.verticalLayout.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(serial_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox.setMaximumSize(QtCore.QSize(400, 400))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(9, 0, -1, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.databit = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databit.sizePolicy().hasHeightForWidth())
        self.databit.setSizePolicy(sizePolicy)
        self.databit.setMaximumSize(QtCore.QSize(70, 20))
        self.databit.setObjectName("databit")
        self.databit.addItem("")
        self.databit.addItem("")
        self.databit.addItem("")
        self.databit.addItem("")
        self.gridLayout.addWidget(self.databit, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.DSR_DTR = QtWidgets.QCheckBox(self.groupBox)
        self.DSR_DTR.setObjectName("DSR_DTR")
        self.gridLayout.addWidget(self.DSR_DTR, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.checkbit = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbit.sizePolicy().hasHeightForWidth())
        self.checkbit.setSizePolicy(sizePolicy)
        self.checkbit.setMaximumSize(QtCore.QSize(130, 20))
        self.checkbit.setIconSize(QtCore.QSize(16, 16))
        self.checkbit.setDuplicatesEnabled(False)
        self.checkbit.setFrame(True)
        self.checkbit.setObjectName("checkbit")
        self.checkbit.addItem("")
        self.checkbit.addItem("")
        self.checkbit.addItem("")
        self.checkbit.addItem("")
        self.checkbit.addItem("")
        self.gridLayout.addWidget(self.checkbit, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.stopbit = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopbit.sizePolicy().hasHeightForWidth())
        self.stopbit.setSizePolicy(sizePolicy)
        self.stopbit.setMaximumSize(QtCore.QSize(70, 20))
        self.stopbit.setObjectName("stopbit")
        self.stopbit.addItem("")
        self.stopbit.addItem("")
        self.stopbit.addItem("")
        self.gridLayout.addWidget(self.stopbit, 3, 1, 1, 1)
        self.XON_XOFF = QtWidgets.QCheckBox(self.groupBox)
        self.XON_XOFF.setObjectName("XON_XOFF")
        self.gridLayout.addWidget(self.XON_XOFF, 4, 2, 1, 1)
        self.RTS_CTS = QtWidgets.QCheckBox(self.groupBox)
        self.RTS_CTS.setObjectName("RTS_CTS")
        self.gridLayout.addWidget(self.RTS_CTS, 4, 1, 1, 1)
        self.sure = QtWidgets.QPushButton(self.groupBox)
        self.sure.setObjectName("sure")
        self.gridLayout.addWidget(self.sure, 5, 0, 1, 1)
        self.cancel = QtWidgets.QPushButton(self.groupBox)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 5, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(serial_window)
        QtCore.QMetaObject.connectSlotsByName(serial_window)

    def retranslateUi(self, serial_window):
        _translate = QtCore.QCoreApplication.translate
        serial_window.setWindowTitle(_translate("serial_window", "串口设置"))
        self.groupBox.setTitle(_translate("serial_window", "串口设置"))
        self.databit.setItemText(0, _translate("serial_window", "8"))
        self.databit.setItemText(1, _translate("serial_window", "7"))
        self.databit.setItemText(2, _translate("serial_window", "6"))
        self.databit.setItemText(3, _translate("serial_window", "5"))
        self.label_3.setText(_translate("serial_window", "检验位"))
        self.DSR_DTR.setText(_translate("serial_window", "DSR/DTR"))
        self.label_5.setText(_translate("serial_window", "数据位"))
        self.checkbit.setItemText(0, _translate("serial_window", "无检验 NONE"))
        self.checkbit.setItemText(1, _translate("serial_window", "偶检验 EVEN"))
        self.checkbit.setItemText(2, _translate("serial_window", "奇检验 ODD"))
        self.checkbit.setItemText(3, _translate("serial_window", "校验位始终为1 MARK"))
        self.checkbit.setItemText(4, _translate("serial_window", "校验位始终为0 SPACE"))
        self.label_4.setText(_translate("serial_window", "停止位"))
        self.stopbit.setItemText(0, _translate("serial_window", "1"))
        self.stopbit.setItemText(1, _translate("serial_window", "1.5"))
        self.stopbit.setItemText(2, _translate("serial_window", "2"))
        self.XON_XOFF.setText(_translate("serial_window", "XON/XOFF"))
        self.RTS_CTS.setText(_translate("serial_window", "RTS/CTS"))
        self.sure.setText(_translate("serial_window", "确定"))
        self.cancel.setText(_translate("serial_window", "取消"))

